version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-node6
      - test-node8
      - test-node10

_test-body: &test-body
  working_directory: ~/workspace
  steps:
    - checkout
    - run:
        name: System Information
        command: |
          echo "Node $(node -v)"
          echo "Yarn v$(yarn --version)"
          node --version > node_version
    - restore_cache:
        key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "node_version" }}
    - run:
        name: Install Dependencies
        command: yarn install
    - save_cache:
        key: v1-{{ .Branch }}-{{ checksum "yarn.lock"}}-{{ checksum "node_version" }}
        paths:
          - ./node_modules
          - ~/.cache/yarn
    - run:
        name: Test
        command: yarn test

_test-and-coverage-body: &test-and-coverage-body
  working_directory: ~/workspace
  steps:
    - checkout
    - run:
        name: System Information
        command: |
          echo "Node $(node -v)"
          echo "Yarn v$(yarn --version)"
          node --version > node_version
    - restore_cache:
        key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "node_version" }}
    - run:
        name: Install Dependencies
        command: yarn install
    - save_cache:
        key: v1-{{ .Branch }}-{{ checksum "yarn.lock"}}-{{ checksum "node_version" }}
        paths:
          - ./node_modules
          - ~/.cache/yarn
    - run:
        name: Type check
        command: yarn typecheck
    - run:
        name: Test & Coverage
        command: yarn coverage

jobs:
  test-node6:
    <<: *test-body
    docker:
      - image: node:6
  test-node8:
    <<: *test-body
    docker:
      - image: node:8
  test-node10:
    <<: *test-and-coverage-body
    docker:
      - image: node:10